import { Inter} from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });



export const metadata = {
  title: "HMPS SI",
  description: "Generated by Indrawan",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" translate="no">
      <body
        className={`${inter.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

